export const routes = {
  login: "/login",
  registration: "/registration",
  twoFaValidate: "/two-fa-validate",
  twoFaVerified: "/two-fa-verified",
  dashboard: "/dashboard",
  exel: "/exel",
  settings: "/settings",
  virtualized: "/virtualized",
  ticTacToe: "/tic-tac-toe",
  supportRequest: "/support_request",
  test: "/test",
  todolistDrag: "/todolist_drag",
  tableOrigin: "/table_origin",
  graphql: "/graphql",
  chess: "/chess",
};
